# Generated by Django 4.0 on 2021-12-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Контракт')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Производитель')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Товар')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Заявка')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('product_list', models.ManyToManyField(to='task.Product')),
                ('сontract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.contract')),
            ],
        ),
    ]
