# Generated by Django 4.0 on 2021-12-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='product_list',
            field=models.ManyToManyField(related_name='products', to='task.Product'),
        ),
    ]
