# Generated by Django 4.0 on 2021-12-22 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_creditapplication_product_list_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditapplication',
            old_name='сontract_id',
            new_name='contract',
        ),
    ]
