# Generated by Django 4.0 on 2021-12-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_сontract_id_creditapplication_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditapplication',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='task.contract'),
        ),
    ]
